enableDebug: false
archiverEnabled: true
nameOverride: ""
fullnameOverride: ""

podSecurityContext:
  {}

sfapmui:
  image:
    repository: snappyflowml/sfapm-ui
    tag: 'v1-1-6'
    pullPolicy: IfNotPresent

