---
enableDebug: false
archiverEnabled: true
nameOverride: ""
fullnameOverride: ""
pprof:
  image:
    repository: snappyflowml/pprof-server
    pullPolicy: IfNotPresent
    tag: 'master-v1-1-12'
podSecurityContext: {}