{{- if .Values.backup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresqlbackup
  labels: {{- include "postgresql.labels" . | nindent 4 }}
data:
{{ tpl (.Files.Glob "scripts/*").AsConfig . | indent 2 }}
{{- end }}