---
enableDebug: false
archiverEnabled: true
nameOverride: ""
fullnameOverride: ""
podSecurityContext: {}
sfapm:
  image:
    repository: snappyflowml/sfapm-server
    tag: '1-0-8'
    pullPolicy: IfNotPresent
sfapmaffinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: role
                operator: In
                values:
                  - server
          topologyKey: kubernetes.io/hostname
disable_server_side_cursors: false