{{- if .Values.global.vizbuilder.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sfapm.fullname" . }}-vizbuilder
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "sfapm.fullname" . }}-vizbuilder
  minReplicas: {{ .Values.global.vizbuilder.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.global.vizbuilder.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.global.vizbuilder.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.global.vizbuilder.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.global.vizbuilder.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.global.vizbuilder.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
