{{- if .Values.sfapmui.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sfapm.fullname" . }}-ui-tls
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
    app: sfapm
    role: ui
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.sfapmui.tls.cert }}
  tls.key: {{ .Values.sfapmui.tls.key }}
{{- end }}
