---
enableDebug: false
archiverEnabled: true
nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []
podAnnotations:
  prometheus.io/scrape: "false"
sidecarLogger:
  enabled: true
  image:
    pullPolicy: Always
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 50m
      memory: 50Mi
serviceAccount:
  create: true
  annotations: {}
  name: ""
  imagePullSecrets: []
  automountServiceAccountToken: false
cloud:
  aws:
    enable: true
  gcs:
    enable: false
    use_google_service_account: true
    service_account: XXXX-compute@developer.gserviceaccount.com OR
      XXXX@XXXX.iam.gserviceaccount.com
    region: us-west1
    zone: us-west1-c
  datacenter:
    enable: false
disable_server_side_cursors: false
postgresql:
  enabled: true
  external:
    dbHost: ""
    dbPort: ""
    dbUser: ""
    dbPassword: ""
  image:
    pullPolicy: IfNotPresent
  rootPassword: postgres
  rootUser: postgres
  multidb: snappyflow;vizbuilder;commands;elasticsearch_manager
  multidbUser: snappyflow
  multidbUserPassord: maplelabs
redis:
  image:
    pullPolicy: IfNotPresent
sfapm:
  replicaCount: 2
  cloud: ""
  ingress:
    enabled: false
    es_user: ""
    es_http: http
    es_host: ""
    es_pass: ""
    es_port: ""
    es_operating_mode: ""
    kafka_api: ""
    arhiver_url: ""
    kafka_user: ""
    kafka_pwd: ""
  azure:
    storage_account_name: ""
    storage_account_key: ""
  service:
    type: ClusterIP
    port: 8000
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 1600
    targetMemoryUtilizationPercentage: 120
vizbuilder:
  service:
    type: ClusterIP
    port: 8000
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
esmanager:
  replicaCount: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 8000
    targetMemoryUtilizationPercentage: 240
  image:
    repository: snappyflowml/sfapm-esmanager
    tag: 1.0.55
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      memory: 768Mi
    requests:
      cpu: 100m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 8000
  warm_movement_rules:
    thresholds:
      - hot_disk_percentage:
          gt: 80
      - hot_store_to_heap:
          gt: 45
    prerequisties: {}
  warm_allocated_freedisk_percent: 80
  min_warm_nodes: 2
  max_relocating_index: 2
  max_shrink_job: 2
  max_forcemerge_job: 2
  max_ongoing_backups: 3
  max_ongoing_restores: 3
esmanager_celery:
  env:
    C_FORCE_ROOT: true
    CELERY_OPTS: -O fair --max-tasks-per-child 200 -P solo
  beat:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 100Mi
    command: celery -A elasticsearch_manager beat --scheduler django -l $LOG_LEVEL
  default:
    resources:
      limits:
        cpu: 1000m
        memory: 768Mi
      requests:
        cpu: 100m
        memory: 100Mi
    replicaCount: 2
    command: celery -A elasticsearch_manager worker -l $LOG_LEVEL -Q
      es_mng_default  $CELERY_OPTS
sfapm_celery:
  env:
    C_FORCE_ROOT: true
    CELERY_OPTS: -O fair --max-tasks-per-child 20 -P gevent
  beat:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 100Mi
    command: celery -A snappyflow beat -l $LOG_LEVEL
  default:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 100Mi
    replicaCount: 1
    command: celery -A snappyflow worker -l $LOG_LEVEL -Q default -c10 $CELERY_OPTS
sfapmaffinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: role
                operator: In
                values:
                  - server
          topologyKey: kubernetes.io/hostname
global:
  sfappname: sf-portal-app
  sfprojectname: snappyflow-app
  sfappname_key: snappyflow/appname
  sfprojectname_key: snappyflow/projectname
  nginx_geo_info_collection: true
  nginx_ua_parsing: true
  enable_sftrace: false
  key: ""
  sfNodeManager:
    enabled: false
    priorityClassName: sf-critical-pod
  sfScheduler:
    enabled: false
    schedulerName: sf-scheduler
