---
enableDebug: false
archiverEnabled: true
nameOverride: ""
fullnameOverride: ""
disable_server_side_cursors: false
podSecurityContext: {}
esmanager:
  image:
    repository: snappyflowml/sfapm-esmanager
    tag: 'master-0-0-4'
    pullPolicy: IfNotPresent
