{{- if .Values.global.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sfapm.serviceAccountName" . }}
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.global.cloud.gcs.enable }}
    iam.gke.io/gcp-service-account: {{ .Values.global.cloud.gcs.service_account }}
    {{- end }}
    {{- with .Values.global.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.global.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.global.serviceAccount.imagePullSecrets }}
  - {{ . }}
  {{- end }}
{{- end }}
automountServiceAccountToken: {{ .Values.global.serviceAccount.automountServiceAccountToken }}
{{- end }}
